package model

// User ...
type User struct {
	// Username ...
	Username string `json:"username" bson:"username"`
	// Email ...
	Email string `json:"email" bson:"email"`
	// PasswordHash ...
	PasswordHash string `json:"-" bson:"password_hash"`
}
